stages:          # List of stages for jobs, and their order of execution
  - deploy

deploy-job:       # This job runs in the build stage, which runs first.
  stage: deploy
  image: maven:3.6.3-openjdk-8
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - mvn clean deploy -Dmaven.test.skip=true


