stages:          # List of stages for jobs, and their order of execution
  - deploy

deploy-job:       # This job runs in the build stage, which runs first.
  stage: deploy
  script:
    - mvn clean deploy
  tags:
    - node2

