default:
  interruptible: true

stages:
  - deploy

deploy-job:
  stage: deploy
  script:
    - mvn clean deploy
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    paths:
      - "urban-common/target/*.jar"
  tags:
    - node2

